### ISSUE TITLE
增加实现导出每个变量在每种离散化方法每个分类数时的Q值功能

### ISSUE THREAD

**Issue by yzlz-yxrj** [stscl/gdverse#33]
能否增加实现导出每个变量在每种离散化方法每个分类数时的Q值功能，如此一来能更方便地绘制折线图，类似于gdm函数

**Comment by SpatLyu** [comment]
You can implement it yourself using a `for` loop or the `purrr` `map` family of functions in combination with `sdsfun::discretize_vector()` and `gdverse::factor_detector()`. I don't intend to add this functionality to `gdverse`, as the goal of `gdverse` is to directly support the GDMs models mentioned in the literature.

**Comment by yzlz-yxrj** [comment]
谢谢
